# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anki_simulator_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from . import graph

class Ui_simulator_dialog(object):
    def setupUi(self, simulator_dialog):
        simulator_dialog.setObjectName("simulator_dialog")
        simulator_dialog.resize(1118, 676)
        self.verticalLayout = QtWidgets.QVBoxLayout(simulator_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbar = QtWidgets.QWidget(simulator_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar.sizePolicy().hasHeightForWidth())
        self.toolbar.setSizePolicy(sizePolicy)
        self.toolbar.setObjectName("toolbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deckChooser = QtWidgets.QWidget(self.toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deckChooser.sizePolicy().hasHeightForWidth())
        self.deckChooser.setSizePolicy(sizePolicy)
        self.deckChooser.setObjectName("deckChooser")
        self.horizontalLayout.addWidget(self.deckChooser)
        self.loadDeckConfigurationsButton = QtWidgets.QPushButton(self.toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadDeckConfigurationsButton.sizePolicy().hasHeightForWidth())
        self.loadDeckConfigurationsButton.setSizePolicy(sizePolicy)
        self.loadDeckConfigurationsButton.setObjectName("loadDeckConfigurationsButton")
        self.horizontalLayout.addWidget(self.loadDeckConfigurationsButton)
        self.verticalLayout.addWidget(self.toolbar)
        self.form = QtWidgets.QWidget(simulator_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.form.sizePolicy().hasHeightForWidth())
        self.form.setSizePolicy(sizePolicy)
        self.form.setObjectName("form")
        self.gridLayout = QtWidgets.QGridLayout(self.form)
        self.gridLayout.setContentsMargins(-1, 12, -1, 12)
        self.gridLayout.setHorizontalSpacing(24)
        self.gridLayout.setObjectName("gridLayout")
        self.startingEaseLabel = QtWidgets.QLabel(self.form)
        self.startingEaseLabel.setObjectName("startingEaseLabel")
        self.gridLayout.addWidget(self.startingEaseLabel, 3, 0, 1, 1)
        self.maximumIntervalSpinbox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximumIntervalSpinbox.sizePolicy().hasHeightForWidth())
        self.maximumIntervalSpinbox.setSizePolicy(sizePolicy)
        self.maximumIntervalSpinbox.setSuffix("")
        self.maximumIntervalSpinbox.setPrefix("")
        self.maximumIntervalSpinbox.setMinimum(1)
        self.maximumIntervalSpinbox.setMaximum(9999)
        self.maximumIntervalSpinbox.setSingleStep(1)
        self.maximumIntervalSpinbox.setProperty("value", 365)
        self.maximumIntervalSpinbox.setObjectName("maximumIntervalSpinbox")
        self.gridLayout.addWidget(self.maximumIntervalSpinbox, 10, 3, 1, 1)
        self.maximumIntervalLabel = QtWidgets.QLabel(self.form)
        self.maximumIntervalLabel.setObjectName("maximumIntervalLabel")
        self.gridLayout.addWidget(self.maximumIntervalLabel, 10, 2, 1, 1)
        self.newLapseIntervalSpinbox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newLapseIntervalSpinbox.sizePolicy().hasHeightForWidth())
        self.newLapseIntervalSpinbox.setSizePolicy(sizePolicy)
        self.newLapseIntervalSpinbox.setPrefix("")
        self.newLapseIntervalSpinbox.setMaximum(100)
        self.newLapseIntervalSpinbox.setSingleStep(10)
        self.newLapseIntervalSpinbox.setProperty("value", 60)
        self.newLapseIntervalSpinbox.setObjectName("newLapseIntervalSpinbox")
        self.gridLayout.addWidget(self.newLapseIntervalSpinbox, 8, 3, 1, 1)
        self.percentCorrectUnseenSpinbox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percentCorrectUnseenSpinbox.sizePolicy().hasHeightForWidth())
        self.percentCorrectUnseenSpinbox.setSizePolicy(sizePolicy)
        self.percentCorrectUnseenSpinbox.setPrefix("")
        self.percentCorrectUnseenSpinbox.setMinimum(0)
        self.percentCorrectUnseenSpinbox.setMaximum(100)
        self.percentCorrectUnseenSpinbox.setSingleStep(1)
        self.percentCorrectUnseenSpinbox.setProperty("value", 30)
        self.percentCorrectUnseenSpinbox.setObjectName("percentCorrectUnseenSpinbox")
        self.gridLayout.addWidget(self.percentCorrectUnseenSpinbox, 2, 6, 1, 1)
        self.graduatingIntervalLabel = QtWidgets.QLabel(self.form)
        self.graduatingIntervalLabel.setObjectName("graduatingIntervalLabel")
        self.gridLayout.addWidget(self.graduatingIntervalLabel, 6, 2, 1, 1)
        self.graduatingIntervalSpinbox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graduatingIntervalSpinbox.sizePolicy().hasHeightForWidth())
        self.graduatingIntervalSpinbox.setSizePolicy(sizePolicy)
        self.graduatingIntervalSpinbox.setSuffix("")
        self.graduatingIntervalSpinbox.setPrefix("")
        self.graduatingIntervalSpinbox.setMinimum(1)
        self.graduatingIntervalSpinbox.setMaximum(9999)
        self.graduatingIntervalSpinbox.setSingleStep(1)
        self.graduatingIntervalSpinbox.setProperty("value", 20)
        self.graduatingIntervalSpinbox.setObjectName("graduatingIntervalSpinbox")
        self.gridLayout.addWidget(self.graduatingIntervalSpinbox, 6, 3, 1, 1)
        self.intervalModifierLabel = QtWidgets.QLabel(self.form)
        self.intervalModifierLabel.setObjectName("intervalModifierLabel")
        self.gridLayout.addWidget(self.intervalModifierLabel, 5, 0, 1, 1)
        self.intervalModifierSpinbox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalModifierSpinbox.sizePolicy().hasHeightForWidth())
        self.intervalModifierSpinbox.setSizePolicy(sizePolicy)
        self.intervalModifierSpinbox.setPrefix("")
        self.intervalModifierSpinbox.setMaximum(999)
        self.intervalModifierSpinbox.setSingleStep(10)
        self.intervalModifierSpinbox.setProperty("value", 100)
        self.intervalModifierSpinbox.setObjectName("intervalModifierSpinbox")
        self.gridLayout.addWidget(self.intervalModifierSpinbox, 5, 1, 1, 1)
        self.percentCorrectYoungLabel = QtWidgets.QLabel(self.form)
        self.percentCorrectYoungLabel.setObjectName("percentCorrectYoungLabel")
        self.gridLayout.addWidget(self.percentCorrectYoungLabel, 6, 4, 1, 1)
        self.percentCorrectYoungSpinbox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percentCorrectYoungSpinbox.sizePolicy().hasHeightForWidth())
        self.percentCorrectYoungSpinbox.setSizePolicy(sizePolicy)
        self.percentCorrectYoungSpinbox.setPrefix("")
        self.percentCorrectYoungSpinbox.setMinimum(1)
        self.percentCorrectYoungSpinbox.setMaximum(100)
        self.percentCorrectYoungSpinbox.setSingleStep(1)
        self.percentCorrectYoungSpinbox.setProperty("value", 90)
        self.percentCorrectYoungSpinbox.setObjectName("percentCorrectYoungSpinbox")
        self.gridLayout.addWidget(self.percentCorrectYoungSpinbox, 6, 6, 1, 1)
        self.percentCorrectMatureLabel = QtWidgets.QLabel(self.form)
        self.percentCorrectMatureLabel.setObjectName("percentCorrectMatureLabel")
        self.gridLayout.addWidget(self.percentCorrectMatureLabel, 8, 4, 1, 1)
        self.learningStepsLabel = QtWidgets.QLabel(self.form)
        self.learningStepsLabel.setObjectName("learningStepsLabel")
        self.gridLayout.addWidget(self.learningStepsLabel, 3, 2, 1, 1)
        self.learningStepsTextfield = QtWidgets.QLineEdit(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.learningStepsTextfield.sizePolicy().hasHeightForWidth())
        self.learningStepsTextfield.setSizePolicy(sizePolicy)
        self.learningStepsTextfield.setMinimumSize(QtCore.QSize(100, 0))
        self.learningStepsTextfield.setObjectName("learningStepsTextfield")
        self.gridLayout.addWidget(self.learningStepsTextfield, 3, 3, 1, 1)
        self.newLapseIntervalLabel = QtWidgets.QLabel(self.form)
        self.newLapseIntervalLabel.setObjectName("newLapseIntervalLabel")
        self.gridLayout.addWidget(self.newLapseIntervalLabel, 8, 2, 1, 1)
        self.lapseStepsTextfield = QtWidgets.QLineEdit(self.form)
        self.lapseStepsTextfield.setMinimumSize(QtCore.QSize(100, 0))
        self.lapseStepsTextfield.setObjectName("lapseStepsTextfield")
        self.gridLayout.addWidget(self.lapseStepsTextfield, 5, 3, 1, 1)
        self.maximumReviewsPerDayLabel = QtWidgets.QLabel(self.form)
        self.maximumReviewsPerDayLabel.setObjectName("maximumReviewsPerDayLabel")
        self.gridLayout.addWidget(self.maximumReviewsPerDayLabel, 2, 2, 1, 1)
        self.newCardsPerDayLabel = QtWidgets.QLabel(self.form)
        self.newCardsPerDayLabel.setObjectName("newCardsPerDayLabel")
        self.gridLayout.addWidget(self.newCardsPerDayLabel, 2, 0, 1, 1)
        self.startingEaseSpinBox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startingEaseSpinBox.sizePolicy().hasHeightForWidth())
        self.startingEaseSpinBox.setSizePolicy(sizePolicy)
        self.startingEaseSpinBox.setPrefix("")
        self.startingEaseSpinBox.setMinimum(130)
        self.startingEaseSpinBox.setMaximum(999)
        self.startingEaseSpinBox.setSingleStep(10)
        self.startingEaseSpinBox.setProperty("value", 250)
        self.startingEaseSpinBox.setObjectName("startingEaseSpinBox")
        self.gridLayout.addWidget(self.startingEaseSpinBox, 3, 1, 1, 1)
        self.percentCorrectLearningLabel = QtWidgets.QLabel(self.form)
        self.percentCorrectLearningLabel.setObjectName("percentCorrectLearningLabel")
        self.gridLayout.addWidget(self.percentCorrectLearningLabel, 3, 4, 1, 1)
        self.maximumReviewsPerDaySpinbox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximumReviewsPerDaySpinbox.sizePolicy().hasHeightForWidth())
        self.maximumReviewsPerDaySpinbox.setSizePolicy(sizePolicy)
        self.maximumReviewsPerDaySpinbox.setSuffix("")
        self.maximumReviewsPerDaySpinbox.setPrefix("")
        self.maximumReviewsPerDaySpinbox.setMinimum(0)
        self.maximumReviewsPerDaySpinbox.setMaximum(9999)
        self.maximumReviewsPerDaySpinbox.setSingleStep(1)
        self.maximumReviewsPerDaySpinbox.setProperty("value", 9999)
        self.maximumReviewsPerDaySpinbox.setObjectName("maximumReviewsPerDaySpinbox")
        self.gridLayout.addWidget(self.maximumReviewsPerDaySpinbox, 2, 3, 1, 1)
        self.lapseStepsLabel = QtWidgets.QLabel(self.form)
        self.lapseStepsLabel.setObjectName("lapseStepsLabel")
        self.gridLayout.addWidget(self.lapseStepsLabel, 5, 2, 1, 1)
        self.percentCorrectLapseLabel = QtWidgets.QLabel(self.form)
        self.percentCorrectLapseLabel.setObjectName("percentCorrectLapseLabel")
        self.gridLayout.addWidget(self.percentCorrectLapseLabel, 5, 4, 1, 1)
        self.percentCorrectLapseTextfield = QtWidgets.QLineEdit(self.form)
        self.percentCorrectLapseTextfield.setMinimumSize(QtCore.QSize(70, 0))
        self.percentCorrectLapseTextfield.setObjectName("percentCorrectLapseTextfield")
        self.gridLayout.addWidget(self.percentCorrectLapseTextfield, 5, 6, 1, 1)
        self.newCardsPerDaySpinbox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newCardsPerDaySpinbox.sizePolicy().hasHeightForWidth())
        self.newCardsPerDaySpinbox.setSizePolicy(sizePolicy)
        self.newCardsPerDaySpinbox.setSuffix("")
        self.newCardsPerDaySpinbox.setPrefix("")
        self.newCardsPerDaySpinbox.setMinimum(0)
        self.newCardsPerDaySpinbox.setMaximum(9999)
        self.newCardsPerDaySpinbox.setSingleStep(1)
        self.newCardsPerDaySpinbox.setProperty("value", 60)
        self.newCardsPerDaySpinbox.setObjectName("newCardsPerDaySpinbox")
        self.gridLayout.addWidget(self.newCardsPerDaySpinbox, 2, 1, 1, 1)
        self.percentCorrectMatureSpinbox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percentCorrectMatureSpinbox.sizePolicy().hasHeightForWidth())
        self.percentCorrectMatureSpinbox.setSizePolicy(sizePolicy)
        self.percentCorrectMatureSpinbox.setPrefix("")
        self.percentCorrectMatureSpinbox.setMinimum(1)
        self.percentCorrectMatureSpinbox.setMaximum(100)
        self.percentCorrectMatureSpinbox.setSingleStep(1)
        self.percentCorrectMatureSpinbox.setProperty("value", 90)
        self.percentCorrectMatureSpinbox.setObjectName("percentCorrectMatureSpinbox")
        self.gridLayout.addWidget(self.percentCorrectMatureSpinbox, 8, 6, 1, 1)
        self.percentCorrectLearningTextfield = QtWidgets.QLineEdit(self.form)
        self.percentCorrectLearningTextfield.setMinimumSize(QtCore.QSize(70, 0))
        self.percentCorrectLearningTextfield.setObjectName("percentCorrectLearningTextfield")
        self.gridLayout.addWidget(self.percentCorrectLearningTextfield, 3, 6, 1, 1)
        self.percentCorrectUnseenLabel = QtWidgets.QLabel(self.form)
        self.percentCorrectUnseenLabel.setObjectName("percentCorrectUnseenLabel")
        self.gridLayout.addWidget(self.percentCorrectUnseenLabel, 2, 4, 1, 1)
        self.includeOverdueCardsCheckbox = QtWidgets.QCheckBox(self.form)
        self.includeOverdueCardsCheckbox.setObjectName("includeOverdueCardsCheckbox")
        self.gridLayout.addWidget(self.includeOverdueCardsCheckbox, 10, 0, 1, 1)
        self.daysToSimulateLabel = QtWidgets.QLabel(self.form)
        self.daysToSimulateLabel.setObjectName("daysToSimulateLabel")
        self.gridLayout.addWidget(self.daysToSimulateLabel, 8, 0, 1, 1)
        self.daysToSimulateSpinbox = QtWidgets.QSpinBox(self.form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daysToSimulateSpinbox.sizePolicy().hasHeightForWidth())
        self.daysToSimulateSpinbox.setSizePolicy(sizePolicy)
        self.daysToSimulateSpinbox.setSuffix("")
        self.daysToSimulateSpinbox.setPrefix("")
        self.daysToSimulateSpinbox.setMinimum(1)
        self.daysToSimulateSpinbox.setMaximum(9999)
        self.daysToSimulateSpinbox.setSingleStep(1)
        self.daysToSimulateSpinbox.setProperty("value", 180)
        self.daysToSimulateSpinbox.setObjectName("daysToSimulateSpinbox")
        self.gridLayout.addWidget(self.daysToSimulateSpinbox, 8, 1, 1, 1)
        self.verticalLayout.addWidget(self.form)
        self.buttons = QtWidgets.QWidget(simulator_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons.sizePolicy().hasHeightForWidth())
        self.buttons.setSizePolicy(sizePolicy)
        self.buttons.setObjectName("buttons")
        self.formLayout = QtWidgets.QFormLayout(self.buttons)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(-1, 2, -1, 2)
        self.formLayout.setObjectName("formLayout")
        self.simulateButton = QtWidgets.QPushButton(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButton.sizePolicy().hasHeightForWidth())
        self.simulateButton.setSizePolicy(sizePolicy)
        self.simulateButton.setObjectName("simulateButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.simulateButton)
        self.clearLastSimulationButton = QtWidgets.QPushButton(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearLastSimulationButton.sizePolicy().hasHeightForWidth())
        self.clearLastSimulationButton.setSizePolicy(sizePolicy)
        self.clearLastSimulationButton.setObjectName("clearLastSimulationButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.clearLastSimulationButton)
        self.verticalLayout.addWidget(self.buttons)
        self.simulationGraph = graph.Graph()
        self.simulationGraph.setMinimumSize(QtCore.QSize(0, 227))
        self.simulationGraph.setObjectName("simulationGraph")
        self.verticalLayout.addWidget(self.simulationGraph)

        self.retranslateUi(simulator_dialog)
        QtCore.QMetaObject.connectSlotsByName(simulator_dialog)
        simulator_dialog.setTabOrder(self.simulateButton, self.newCardsPerDaySpinbox)
        simulator_dialog.setTabOrder(self.newCardsPerDaySpinbox, self.startingEaseSpinBox)
        simulator_dialog.setTabOrder(self.startingEaseSpinBox, self.intervalModifierSpinbox)
        simulator_dialog.setTabOrder(self.intervalModifierSpinbox, self.maximumReviewsPerDaySpinbox)
        simulator_dialog.setTabOrder(self.maximumReviewsPerDaySpinbox, self.learningStepsTextfield)
        simulator_dialog.setTabOrder(self.learningStepsTextfield, self.lapseStepsTextfield)
        simulator_dialog.setTabOrder(self.lapseStepsTextfield, self.graduatingIntervalSpinbox)
        simulator_dialog.setTabOrder(self.graduatingIntervalSpinbox, self.newLapseIntervalSpinbox)
        simulator_dialog.setTabOrder(self.newLapseIntervalSpinbox, self.maximumIntervalSpinbox)
        simulator_dialog.setTabOrder(self.maximumIntervalSpinbox, self.percentCorrectUnseenSpinbox)
        simulator_dialog.setTabOrder(self.percentCorrectUnseenSpinbox, self.percentCorrectLearningTextfield)
        simulator_dialog.setTabOrder(self.percentCorrectLearningTextfield, self.percentCorrectLapseTextfield)
        simulator_dialog.setTabOrder(self.percentCorrectLapseTextfield, self.percentCorrectYoungSpinbox)
        simulator_dialog.setTabOrder(self.percentCorrectYoungSpinbox, self.percentCorrectMatureSpinbox)
        simulator_dialog.setTabOrder(self.percentCorrectMatureSpinbox, self.loadDeckConfigurationsButton)
        simulator_dialog.setTabOrder(self.loadDeckConfigurationsButton, self.clearLastSimulationButton)

    def retranslateUi(self, simulator_dialog):
        _translate = QtCore.QCoreApplication.translate
        simulator_dialog.setWindowTitle(_translate("simulator_dialog", "Anki Simulator"))
        self.loadDeckConfigurationsButton.setText(_translate("simulator_dialog", "Load deck configurations"))
        self.startingEaseLabel.setText(_translate("simulator_dialog", "Starting ease"))
        self.maximumIntervalLabel.setText(_translate("simulator_dialog", "Maximum interval (days)"))
        self.newLapseIntervalSpinbox.setSuffix(_translate("simulator_dialog", "%"))
        self.percentCorrectUnseenSpinbox.setSuffix(_translate("simulator_dialog", "%"))
        self.graduatingIntervalLabel.setText(_translate("simulator_dialog", "Graduating interval (days)"))
        self.intervalModifierLabel.setText(_translate("simulator_dialog", "Interval modifier"))
        self.intervalModifierSpinbox.setSuffix(_translate("simulator_dialog", "%"))
        self.percentCorrectYoungLabel.setText(_translate("simulator_dialog", "% correct young cards"))
        self.percentCorrectYoungSpinbox.setSuffix(_translate("simulator_dialog", "%"))
        self.percentCorrectMatureLabel.setText(_translate("simulator_dialog", "% correct mature cards"))
        self.learningStepsLabel.setText(_translate("simulator_dialog", "Learning steps"))
        self.learningStepsTextfield.setText(_translate("simulator_dialog", "30 2880 8640"))
        self.newLapseIntervalLabel.setText(_translate("simulator_dialog", "New lapse interval"))
        self.lapseStepsTextfield.setText(_translate("simulator_dialog", "1440"))
        self.maximumReviewsPerDayLabel.setText(_translate("simulator_dialog", "Maximum reviews per day"))
        self.newCardsPerDayLabel.setText(_translate("simulator_dialog", "New cards per day"))
        self.startingEaseSpinBox.setSuffix(_translate("simulator_dialog", "%"))
        self.percentCorrectLearningLabel.setText(_translate("simulator_dialog", "% correct learning steps"))
        self.lapseStepsLabel.setText(_translate("simulator_dialog", "Lapse steps"))
        self.percentCorrectLapseLabel.setText(_translate("simulator_dialog", "% correct lapse steps"))
        self.percentCorrectLapseTextfield.setText(_translate("simulator_dialog", "90 90"))
        self.percentCorrectMatureSpinbox.setSuffix(_translate("simulator_dialog", "%"))
        self.percentCorrectLearningTextfield.setText(_translate("simulator_dialog", "90 90 90"))
        self.percentCorrectUnseenLabel.setText(_translate("simulator_dialog", "% correct unseen cards"))
        self.includeOverdueCardsCheckbox.setText(_translate("simulator_dialog", "Include overdue cards"))
        self.daysToSimulateLabel.setText(_translate("simulator_dialog", "Days to simulate"))
        self.simulateButton.setText(_translate("simulator_dialog", "Simulate"))
        self.clearLastSimulationButton.setText(_translate("simulator_dialog", "Clear last simulation"))
